# Welcome to Jekyll!

# Website settings
title: "ENESY"
description: "Cộng đồng các Kỹ sư đam mê lập trình."
keywords: "enesy,enesyteam,laptrinh"
baseurl: "/"
url: "https://enesyteam.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Enesy Team'
  first_name: 'Team'
  last_name: 'Enesy'
  email: 'congnvc@gmail.com'
  facebook_username: 'hkscd'
  github_username: 'enesyteam'
  head_img: 'static/img/landing/enesy.jpg'
  desc: 'ENESY Team là một nhóm các Kỹ sư cầu đường đam mê lập trình, chúng tôi luôn nỗ lực không ngừng để tạo ra các công cụ hỗ trợ đắc lực cho công việc của mình. Hơn thế nữa, chúng tôi mong muốn chia sẻ đến cộng đồng những điều tốt đẹp nhất. Hãy tham gia Enesy Team ngay hôm nay!'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

 # - id: 'career'
 #   i18n: 'nav.career'
 #   name: 'Career'
 #   tpl: 'career.html'
 #   css: 'timeline'

 # - id: 'skills'
 #   i18n: 'nav.skills'
 #   name: 'Skills'
 #   tpl: 'skills.html'
 #   css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'vi'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: enesyteam
  public_key: 2dSo1yG1Nz3lYRQMbpggC2worQxHjbNkvJnTY3gLReM91zsDp8FkqOrJ2ZmjXukl

# share
bshare:
  uuid: 

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: 

# growingIO
gio:
  id: 

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
