language: ruby

cache: bundler

sudo: false

rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3

gemfile:
  - gemfiles/jekyll_v1.gemfile
  - gemfiles/jekyll_v2.gemfile
  - gemfiles/jekyll_v3.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/jekyll_v3.gemfile
